// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlpXrPpz4oPZN4d8qRtYbaHMoKbgUowTA',
    appId: '1:969551023282:web:1388d189de9ae9f1fc4dab',
    messagingSenderId: '969551023282',
    projectId: 'travello-4f39d',
    authDomain: 'travello-4f39d.firebaseapp.com',
    storageBucket: 'travello-4f39d.firebasestorage.app',
    measurementId: 'G-6YJFTQSVSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCms4ijswzzkAcQs_ad_wNSpRYQswHrA9M',
    appId: '1:969551023282:android:e8572c65f5ce6c07fc4dab',
    messagingSenderId: '969551023282',
    projectId: 'travello-4f39d',
    storageBucket: 'travello-4f39d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB8xNPwZOfXiXD137Wvl9-1dk-iqYXDJg',
    appId: '1:969551023282:ios:a2f665938c93c97efc4dab',
    messagingSenderId: '969551023282',
    projectId: 'travello-4f39d',
    storageBucket: 'travello-4f39d.firebasestorage.app',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB8xNPwZOfXiXD137Wvl9-1dk-iqYXDJg',
    appId: '1:969551023282:ios:a2f665938c93c97efc4dab',
    messagingSenderId: '969551023282',
    projectId: 'travello-4f39d',
    storageBucket: 'travello-4f39d.firebasestorage.app',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlpXrPpz4oPZN4d8qRtYbaHMoKbgUowTA',
    appId: '1:969551023282:web:6f0a1d9e606b68d9fc4dab',
    messagingSenderId: '969551023282',
    projectId: 'travello-4f39d',
    authDomain: 'travello-4f39d.firebaseapp.com',
    storageBucket: 'travello-4f39d.firebasestorage.app',
    measurementId: 'G-KYELLV06WF',
  );
}